CREATE DATABASE School;
USE School;

CREATE TABLE User (
    user_id INTEGER NOTNULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(128) UNIQUE,
    name VARCHAR(128)
)

CREATE TABLE Course(
    course_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(128) UNIQUE
) 

CREATE TABLE Member(
    FOREIGN KEY (user_id) REFERENCES User(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (course_id) REFERENCES Course(course_id) ON DELETE CASCADE ON UPDATE CASCADE,

    PRIMAY KEY (user_id,course_id)
)




